import React, { useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { jsPDF } from 'jspdf'
import { countries } from '../data/countries'
import { CheckCircle, ArrowLeft, ArrowRight, BookOpen, FileText, Landmark, PlaneTakeoff, GraduationCap } from 'lucide-react'

const CountryDetail = () => {
  const { id } = useParams()
  const country = countries.find(c => c.id === id)

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [id])

  const handleDownloadPDF = () => {
    if (!country) return

    const doc = new jsPDF()
    const margin = 20
    let y = 20

    // Title
    doc.setFontSize(22)
    doc.setTextColor(0, 102, 255) // Primary color
    doc.text(`${country.name} Visa Guide`, margin, y)
    y += 15

    // Description
    doc.setFontSize(12)
    doc.setTextColor(100, 116, 139) // Slate-500
    const splitDescription = doc.splitTextToSize(country.fullDescription || country.description, 170)
    doc.text(splitDescription, margin, y)
    y += splitDescription.length * 7 + 10

    // Benefits
    doc.setFontSize(16)
    doc.setTextColor(15, 23, 42) // Slate-900
    doc.text(`Why Study in ${country.name}?`, margin, y)
    y += 10
    doc.setFontSize(11)
    doc.setTextColor(51, 65, 85) // Slate-700
    country.benefits.forEach((benefit) => {
      doc.text(`• ${benefit}`, margin + 5, y)
      y += 7
    })
    y += 10

    // Requirements
    doc.setFontSize(16)
    doc.setTextColor(15, 23, 42)
    doc.text('Key Requirements', margin, y)
    y += 10
    doc.setFontSize(11)
    country.requirements.forEach((req) => {
      doc.text(`• ${req}`, margin + 5, y)
      y += 7
    })
    y += 15

    // Process
    doc.setFontSize(16)
    doc.setTextColor(15, 23, 42)
    doc.text('Application Process', margin, y)
    y += 10
    doc.setFontSize(11)
    country.process.forEach((step) => {
      const stepText = `${step.step}. ${step.title}: ${step.description}`
      const splitStep = doc.splitTextToSize(stepText, 160)
      doc.text(splitStep, margin + 5, y)
      y += splitStep.length * 7 + 3
    })

    // Footer
    doc.setFontSize(10)
    doc.setTextColor(148, 163, 184) // Slate-400
    doc.text('Generated by Hometown Careers | +91 9996236151', margin, 280)

    doc.save(`${country.name}_Visa_Guide.pdf`)
  }

  if (!country) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-display font-bold text-slate-900">Country Not Found</h2>
          <Link to="/" className="btn-primary">Back to Home</Link>
        </div>
      </div>
    )
  }

  return (
    <div className="pt-32 pb-24">
      {/* Hero Section */}
      <section className="relative h-[60vh] min-h-[400px] mb-20 overflow-hidden">
        <div className="absolute inset-0 z-0">
          <img 
            src={country.image} 
            alt={country.name} 
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-[2px]" />
        </div>
        
        <div className="section-container relative z-10 h-full flex flex-col justify-end pb-12">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            <Link to="/#destinations" className="inline-flex items-center gap-2 text-white/80 hover:text-white transition-colors mb-4 text-sm font-medium">
              <ArrowLeft className="w-4 h-4" />
              Back to Destinations
            </Link>
            <div className="flex items-center gap-4">
              <span className="text-5xl md:text-6xl">{country.flag}</span>
              <h1 className="text-5xl md:text-7xl font-display font-bold text-white tracking-tight">
                {country.name}
              </h1>
            </div>
            <p className="text-xl text-white/90 max-w-2xl font-medium leading-relaxed">
              {country.description}
            </p>
          </motion.div>
        </div>
      </section>

      <div className="section-container">
        <div className="grid lg:grid-cols-3 gap-16">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-16">
            {/* Overview */}
            <section className="space-y-6">
              <h2 className="text-3xl font-display font-bold text-slate-900 flex items-center gap-3">
                <BookOpen className="w-8 h-8 text-primary" />
                Overview
              </h2>
              <p className="text-slate-600 text-lg leading-relaxed">
                {country.fullDescription}
              </p>
            </section>

            {/* Benefits */}
            <section className="space-y-8">
              <h2 className="text-3xl font-display font-bold text-slate-900 flex items-center gap-3">
                <CheckCircle className="w-8 h-8 text-primary" />
                Why Study in {country.name}?
              </h2>
              <div className="grid md:grid-cols-2 gap-6">
                {country.benefits.map((benefit, i) => (
                  <motion.div 
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="flex gap-4 p-6 rounded-2xl bg-white border border-slate-100 shadow-sm"
                  >
                    <div className="w-6 h-6 rounded-full bg-green-100 flex items-center justify-center shrink-0 mt-1">
                      <CheckCircle className="w-4 h-4 text-green-600" />
                    </div>
                    <p className="text-slate-700 font-medium">{benefit}</p>
                  </motion.div>
                ))}
              </div>
            </section>

            {/* Process Timeline */}
            <section className="space-y-10">
              <h2 className="text-3xl font-display font-bold text-slate-900 flex items-center gap-3">
                <PlaneTakeoff className="w-8 h-8 text-primary" />
                Application Process
              </h2>
              <div className="relative space-y-8 before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-primary before:via-primary/20 before:to-transparent">
                {country.process.map((step, i) => (
                  <div key={i} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group">
                    <div className="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-primary text-white shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2">
                      <span className="font-bold">{step.step}</span>
                    </div>
                    <div className="w-[calc(100%-4rem)] md:w-[45%] p-6 rounded-2xl bg-white border border-slate-100 shadow-sm hover:border-primary/30 transition-colors">
                      <h3 className="text-xl font-display font-bold text-slate-900 mb-2">{step.title}</h3>
                      <p className="text-slate-500 text-sm leading-relaxed">{step.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          </div>

          {/* Sidebar */}
          <div className="space-y-8">
            {/* Requirements Card */}
            <div className="p-8 rounded-3xl bg-slate-900 text-white space-y-8 shadow-xl">
              <h3 className="text-2xl font-display font-bold flex items-center gap-3">
                <FileText className="w-6 h-6 text-primary" />
                Key Requirements
              </h3>
              <ul className="space-y-4">
                {country.requirements.map((req, i) => (
                  <li key={i} className="flex gap-3 text-white/80 text-sm">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 shrink-0" />
                    {req}
                  </li>
                ))}
              </ul>
              <button 
                onClick={handleDownloadPDF}
                className="w-full btn-primary py-4 justify-center"
              >
                Download PDF Guide
              </button>
            </div>

            {/* CTA Card */}
            <div className="p-8 rounded-3xl bg-primary/5 border border-primary/10 space-y-6">
              <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center">
                <GraduationCap className="w-6 h-6 text-primary" />
              </div>
              <h3 className="text-2xl font-display font-bold text-slate-900">Start Your Application Today</h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                Get a free consultation with our experts to understand your eligibility and start your journey to {country.name}.
              </p>
              <button className="w-full btn-primary py-4 justify-center gap-2 group">
                Book Free Consultation
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default CountryDetail
